In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot
import scipy as sp
import sklearn as skl
 
import tensorflow as tf

In [52]:
full_data = pd.read_csv('Datasets/Real-Time_Road_Conditions.csv')
null_data = pd.read_csv('data_selected_indexes_in_5_columns_0.2_rows_0.5_0.20371799465636653')

In [53]:
percentage_of_rows_to_select = 0.5
total_rows_to_select = int(np.floor(full_data.count()[0]*percentage_of_rows_to_select))
full_data = full_data[:total_rows_to_select]

In [54]:
null_data.drop(columns=['Unnamed: 0'], inplace=True)
# null_data.drop(columns=['timestamp'], inplace=True)
null_data.head()

       Location Name  voltage_y  voltage_x  voltage_ratio  air_temp_secondary
0                NaN        NaN        NaN            NaN                 NaN
1  11TH ST / 35 SVRD        NaN        NaN            NaN                0.21
2                NaN        NaN        NaN            NaN                 NaN
3                NaN        NaN        NaN            NaN                 NaN
4                NaN        NaN        NaN            NaN               -1.47

In [55]:
full_columns = full_data.columns
null_columns = null_data.columns

In [56]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [57]:
# manual one hot encoding

# label_encoder = LabelEncoder()
# new_target = label_encoder.fit_transform(full_data['Location Name'])
# OneHotEncoder().fit(new_target.reshape(-1,1))

# OneHotEncoder().fit_transform(new_target.reshape(-1,1)).toarray()

In [58]:
# full data with null datum in selected columns
for column in full_columns:
    if column in null_columns:
        full_data[column] = null_data[column]

In [59]:
# full_data.drop(columns=['timestamp'], inplace=True)
## removing id, sensor_id, location 
full_data.drop(columns=['id', 'sensor_id', 'Location', 'timestamp'], inplace=True)

In [60]:
full_data.isna().sum()

Location Name               524713
voltage_y                   524713
voltage_x                   524713
voltage_ratio               524713
air_temp_secondary          524713
temp_surface                     0
condition_code_displayed         0
condition_code_measured          0
condition_text_displayed         0
condition_text_measured          0
friction_code_displayed          0
friction_code_measured           0
friction_value_displayed         0
friction_value_measured          0
dirty_lens_score                 0
grip_text                        0
relative_humidity                0
air_temp_primary                 0
air_temp_tertiary                0
status_code                      0
dtype: int64

In [61]:
full_data.dtypes

Location Name                object
voltage_y                   float64
voltage_x                   float64
voltage_ratio               float64
air_temp_secondary          float64
temp_surface                float64
condition_code_displayed      int64
condition_code_measured       int64
condition_text_displayed     object
condition_text_measured      object
friction_code_displayed       int64
friction_code_measured        int64
friction_value_displayed    float64
friction_value_measured     float64
dirty_lens_score              int64
grip_text                    object
relative_humidity           float64
air_temp_primary            float64
air_temp_tertiary           float64
status_code                   int64
dtype: object

In [62]:
columns_to_encode = ['Location Name', 'condition_text_displayed', 'condition_text_measured', 'grip_text']
full_data = pd.get_dummies(full_data, columns=['Location Name', 'condition_text_displayed', 'condition_text_measured', 'grip_text'])

In [63]:
full_data

,voltage_y,voltage_x,voltage_ratio,air_temp_secondary,temp_surface,condition_code_displayed,condition_code_measured,friction_code_displayed,friction_code_measured,friction_value_displayed,...,condition_text_measured_SN1,condition_text_measured_UNK,condition_text_measured_WT1,condition_text_measured_WT2,condition_text_measured_WT3,grip_text_ FAIR,grip_text_ GOOD,grip_text_FAIR,grip_text_GOOD,grip_text_POOR
0,NaN,NaN,NaN,NaN,0.51,1,1,3,3,0.70,...,0,0,0,0,0,0,0,0,1,0
1,NaN,NaN,NaN,0.21,0.35,1,1,8,8,0.70,...,0,0,0,0,0,0,0,0,1,0
2,NaN,NaN,NaN,NaN,0.41,1,1,8,29,0.70,...,0,0,0,0,0,0,0,0,1,0
3,NaN,NaN,NaN,NaN,-0.97,1,1,3,3,0.70,...,0,0,0,0,0,0,0,0,1,0
4,NaN,NaN,NaN,-1.47,-0.93,1,1,3,3,0.70,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655887,NaN,NaN,NaN,NaN,14.43,2,2,10,9,0.63,...,0,0,1,0,0,0,0,0,1,0
655888,NaN,NaN,NaN,13.27,13.65,2,2,11,11,0.60,...,0,0,1,0,0,0,0,0,1,0
655889,NaN,NaN,NaN,25.53,26.25,1,1,2,2,0.82,...,0,0,0,0,0,0,0,0,1,0
655890,NaN,NaN,NaN,20.95,20.91,1,1,2,2,0.82,...,0,0,0,0,0,0,0,0,1,0
655891,NaN,NaN,NaN,NaN,24.23,1,1,2,2,0.82,...,0,0,0,0,0,0,0,0,1,0

In [64]:
from sklearn.impute import KNNImputer

In [65]:
imputer = KNNImputer(n_neighbors=5)

In [66]:
# model = imputer.fit(full_data)

In [67]:
after_imputing = imputer.fit_transform(full_data)

In [68]:
after_imputing

array([[1.3576e+03, 1.5440e+03, 8.8160e-01, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [2.6112e+03, 2.1946e+03, 1.1774e+00, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [1.9306e+03, 1.6452e+03, 1.3768e+00, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       ...,
       [2.3014e+03, 2.4452e+03, 1.0462e+00, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [2.2500e+03, 2.0448e+03, 1.1056e+00, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [2.3842e+03, 2.2320e+03, 1.0952e+00, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00]])

In [70]:
import pickle

with open('after_imputing_50.pkl', 'wb') as file:
    pickle.dump(after_imputing, file)

In [78]:
import miceforest as mif

# !pip install blosc

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [82]:
rf_imputed_data = mif.ampute_data(full_data,perc=0.20)

In [81]:
full_data

,voltage_y,voltage_x,voltage_ratio,air_temp_secondary,temp_surface,condition_code_displayed,condition_code_measured,friction_code_displayed,friction_code_measured,friction_value_displayed,...,condition_text_measured_SN1,condition_text_measured_UNK,condition_text_measured_WT1,condition_text_measured_WT2,condition_text_measured_WT3,grip_text_ FAIR,grip_text_ GOOD,grip_text_FAIR,grip_text_GOOD,grip_text_POOR
0,NaN,NaN,NaN,NaN,0.51,1,1,3,3,0.70,...,0,0,0,0,0,0,0,0,1,0
1,NaN,NaN,NaN,0.21,0.35,1,1,8,8,0.70,...,0,0,0,0,0,0,0,0,1,0
2,NaN,NaN,NaN,NaN,0.41,1,1,8,29,0.70,...,0,0,0,0,0,0,0,0,1,0
3,NaN,NaN,NaN,NaN,-0.97,1,1,3,3,0.70,...,0,0,0,0,0,0,0,0,1,0
4,NaN,NaN,NaN,-1.47,-0.93,1,1,3,3,0.70,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655887,NaN,NaN,NaN,NaN,14.43,2,2,10,9,0.63,...,0,0,1,0,0,0,0,0,1,0
655888,NaN,NaN,NaN,13.27,13.65,2,2,11,11,0.60,...,0,0,1,0,0,0,0,0,1,0
655889,NaN,NaN,NaN,25.53,26.25,1,1,2,2,0.82,...,0,0,0,0,0,0,0,0,1,0
655890,NaN,NaN,NaN,20.95,20.91,1,1,2,2,0.82,...,0,0,0,0,0,0,0,0,1,0
655891,NaN,NaN,NaN,NaN,24.23,1,1,2,2,0.82,...,0,0,0,0,0,0,0,0,1,0

In [84]:
# mif.ImputationKernel
# Create kernel. 
kds = mif.ImputationKernel(
  rf_imputed_data,
  save_all_iterations=True,
)

# Run the MICE algorithm for 3 iterations
kds.mice(3)

# Return the completed kernel data
rf_complete_data = kds.complete_data()

In [85]:
rf_complete_dataim

,voltage_y,voltage_x,voltage_ratio,air_temp_secondary,temp_surface,condition_code_displayed,condition_code_measured,friction_code_displayed,friction_code_measured,friction_value_displayed,...,condition_text_measured_SN1,condition_text_measured_UNK,condition_text_measured_WT1,condition_text_measured_WT2,condition_text_measured_WT3,grip_text_ FAIR,grip_text_ GOOD,grip_text_FAIR,grip_text_GOOD,grip_text_POOR
0,1540.0,1698.0,0.892,-0.11,0.51,1.0,1.0,3.0,3.0,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2182.0,2120.0,1.149,0.21,0.35,1.0,1.0,8.0,8.0,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2875.0,2424.0,1.432,0.27,0.41,1.0,1.0,8.0,29.0,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1637.0,1570.0,1.030,-1.47,-0.97,1.0,1.0,3.0,3.0,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1609.0,1626.0,1.064,-1.47,-0.93,1.0,1.0,3.0,3.0,0.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655887,1105.0,883.0,1.259,14.39,14.43,2.0,2.0,10.0,9.0,0.63,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
655888,967.0,613.0,1.649,13.27,13.69,2.0,2.0,11.0,11.0,0.60,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
655889,1995.0,2029.0,1.017,25.53,26.25,1.0,1.0,2.0,2.0,0.82,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
655890,2255.0,2004.0,1.104,20.95,20.91,1.0,1.0,2.0,2.0,0.82,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
655891,2098.0,1935.0,1.061,21.77,24.23,1.0,1.0,2.0,2.0,0.82,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0